changelog:
  exclude:
    labels:
      - github-actions
      - duplicate
      - wontfix
      - invalid
      - question
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
        - breaking
        - major
    - title: ✨ New Features
      labels:
        - enhancement
        - feature
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
        - patch
    - title: 🔧 Maintenance
      labels:
        - chore
        - dependencies
        - maintenance
        - refactor
        - perf
        - build
        - ci
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🧪 Tests
      labels:
        - test
        - tests
    - title: 🎨 Styles
      labels:
        - style
        - ui
        - ux
    - title: 🔄 Other Changes
      labels:
        - "*"
